import 'bootstrap/dist/css/bootstrap.min.css'
import BootstrapClient from '@/app/BootstrapClient'; // Client component import
import Script from 'next/script';
import "@/public/assets/styles.css"
import Alert from './component/Alert';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {
        <Script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"/>
      }
      <body >
        {children}
        <Alert/>
        <BootstrapClient/>
      </body>
    </html>
  );
}
