import 'bootstrap/dist/css/bootstrap.min.css'
import BootstrapClient from '@/app/BootstrapClient'; // Client component import

import "@/public/assets/styles.css"
import Alert from './component/Alert';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
        <Alert/>
        <BootstrapClient/>
      </body>
    </html>
  );
}
